### ISSUE TITLE
App broken due to new UI changes in the mobile version of DeepL

### ISSUE THREAD

**Issue by adarsh1001** [sakusaku3939/DeepLAndroid#19]
DeepL did some UI changes to the mobile version of their website. The app seems to have broken because of those changes.

![Screenshot_20210702-124521.png](https://user-images.githubusercontent.com/8820038/124236297-e7944100-db33-11eb-8821-eb1ccb231d49.png)

What doesn't work:
- Language selection toolbar is missing.
- Translation via app.
- Translation via floating text selection action.

App version: v4.0

**Comment by sakusaku3939** [comment]
Thanks for the info. I'll try to fix it later.👍

**Comment by sakusaku3939** [comment]
After investigating, we found that the cause was apparently an update to the DeepL server that required Web Storage permissions.
I fixed those and it works well with the new design!

These changes have been incorporated into v4.0:
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v4.0

**Comment by KoumiCZ** [comment]
It works! 🤗

**Comment by sakusaku3939** [comment]
I will keep this issue open again until the new version is reflected in F-Droid so that people with the same problem can resolve it👌

**Comment by dorpauli** [comment]
Hello,

it is still not working for me after upgrading to 4.0 fdroid version. I also tried to reinstall it.

**Comment by eredrolo** [comment]
F-Droid got the 4.0 update and it's still not working for me. But the GitHub release is working.

**Comment by sakusaku3939** [comment]
@eredrolo After uploading v4.0, we replaced it with a modified version of the same version a day later. However, in some cases, this may not be retrieved well by F-Droid, so I have just released v4.1 with other changes.
Sorry if v4.0 doesn't replace the new one! Please wait a little longer.

**Comment by eredrolo** [comment]
@sakusaku3939 Thanks. I will just use the GitHub release until F-Droid is updated.

**Comment by ShareASmile** [comment]
Happy to report As of 7-7-2021 Fdroid is reflecting New modified version v4.0 (13) & it is working.

But one question:
Does DeepL Translator supports any Indian Language Translation?
..as any Indian Language does not show in Language selection toolbar.

**Comment by sakusaku3939** [comment]
@ShareASmile Thanks for the report! I'm glad it's reflected. 
Now that the problem is solved, I'll close this thread. 

Regarding your question: it seems that Deepl translation is not yet supported for Indian languages 🙃
